#schema.yml 

version: 2

sources:
  - name: raw
    schema: gz_raw_data

    tables: 
      - name: product
        identifier: raw_gz_product 
        description: Table Greenweez données brutes sur les id produits et purchase price
        columns: 
        - name: products_id
        - name: purchSE_PRICE
        config:
          alias: product 

      - name: sales
        identifier: raw_gz_sales 
        description : tables greenweez sur les commandes, revenue et quantités vendues
        columns:
          - name: date_date
          - name:  orders_id
          - name: pdt_id
          - name: revenue 
          - name: quantity 

      - name : ship
        identifier: raw_gz_ship 
        description: Table de donnée Greenweez sur les shipping et livraison
        columns:
          - name: orders_id
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost

