#schema.yml 

version: 2

sources:
  - name: raw
    schema: gz_raw_data

    tables: 
      - name: product
        identifier: raw_gz_product 
        description: Table Greenweez données brutes sur les id produits et purchase price
        columns: 
        - name: products_id
          description: id des produits 
          tests:
            - unique
            - not_null
        - name: purchSE_PRICE
          description: prix du produit
          

      - name: sales
        identifier: raw_gz_sales 
        description : tables greenweez sur les commandes, revenue et quantités vendues
        
        # Freshness testing :
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after:
            count: 90
            period: day
        

        columns:
          - name: date_date
            description: date de l'achat
          - name:  orders_id
            description: id de la commande
          - name: pdt_id
            description: id du produit
          - name: revenue 
            description: montant de la commande 
          - name: quantity 
            description: quantité de produits achetés 
        tests:
          #- unique:
              #colunm_name: "(orders_id ||'-'|| pdt_id)"
          - not_null:
              column_name: "(orders_id ||'-'|| pdt_id)"

      - name : ship
        identifier: raw_gz_ship 
        description: Table de donnée Greenweez sur les shipping et livraison
        columns:
          - name: orders_id
            description: id de la commande
            tests:
            - unique
            - not_null
          - name: shipping_fee
            description: frais d'expédition
          - name: logCost
            description: coût logistique 
          - name: ship_cost
            description: coût d'envoi

      - name: adwords
        identifier: raw_gz_adwords 
        description: Table données brutes campagnes Adwords
        columns: 
        - name: date_date
          description: date 
        - name: paid_source
          description: source de données 
        - name: campaign_key
          description: id de la campagne 
        - name: camPGN_name
          description: nom de la campagne
        - name: ads_cost
          description: spend de la campagne
        - name: impression
          description: click 
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"

      - name: bing
        identifier: raw_gz_bing 
        description: Table données brutes campagnes Adwords
        columns: 
        - name: date_date
          description: date 
        - name: paid_source
          description: source de données 
        - name: campaign_key
          description: id de la campagne 
        - name: camPGN_name
          description: nom de la campagne
        - name: ads_cost
          description: spend de la campagne
        - name: impression
          description: click 
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"

      - name: criteo
        identifier: raw_gz_criteo
        description: Table données brutes campagnes Adwords
        columns: 
        - name: date_date
          description: date 
        - name: paid_source
          description: source de données 
        - name: campaign_key
          description: id de la campagne 
        - name: camPGN_name
          description: nom de la campagne
        - name: ads_cost
          description: spend de la campagne
        - name: impression
          description: click 
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"
    
      - name: facebook
        identifier: raw_gz_facebook
        description: Table données brutes campagnes Adwords
        columns: 
        - name: date_date
          description: date 
        - name: paid_source
          description: source de données 
        - name: campaign_key
          description: id de la campagne 
        - name: camPGN_name
          description: nom de la campagne
        - name: ads_cost
          description: spend de la campagne
        - name: impression
          description: click 
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
          - not_null:
              column_name: "(date_date || '-' || campaign_key)"

models: 
  - name: int_orders_margin
    description: Orders margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_orders_operational
    description: Orders operational margin details.
    columns:
      - name: orders_id
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_sales_margin
    description: Sales margin details.
    columns:
      - name: orders_id
        description: Identifiant de commande.
        tests:
          - not_null

  - name: finance_days
    description: Finance days info.
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns
    description: Union de toutes les sources
    columns:
      - name: "(date_date || '-' || campaign_key)"
        description: Primary key.
        tests:
          - unique
          - not_null

  - name: int_campaigns_day
    description: daily total sources.
    columns:
      - name: date_date
        description: Primary key.
        tests:
          - unique
          - not_null




